[package]
name = "yawada"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.5.3"
chrono = "0.4.38"
directories = "5.0.1"
dirs = "5.0.1"
eframe = "0.28.1"
egui = "0.28.1"
egui-modal = "0.4.0"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
